server:
  port: 6001
spring:
  application:
    name: eureka_client_customer_6001
eureka:
  client:
#    register-with-eureka: true
    hostname: eureka_client_customer_6001
    prefer-ip-address: true
    service-url:
      # 集群注册中心
      defaultZone: http://registry01.com:7001/eureka/,http://registry02.com:7002/eureka/
feign:
  hystrix:
    enabled: true