server:
  port: 8001
spring:
  application:
    name: eureka-client-provider
eureka:
  instance:
    hostname: eureka-client-provider-8001
    prefer-ip-address: true
  client:
    service-url:
      # 集群注册中心
      defaultZone: http://registry01.com:7001/eureka/,http://registry02.com:7002/eureka/